// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cns/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryRegisteredChainRequest struct {
	ChainID string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (m *QueryRegisteredChainRequest) Reset()         { *m = QueryRegisteredChainRequest{} }
func (m *QueryRegisteredChainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredChainRequest) ProtoMessage()    {}
func (*QueryRegisteredChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{2}
}
func (m *QueryRegisteredChainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredChainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredChainRequest.Merge(m, src)
}
func (m *QueryRegisteredChainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredChainRequest proto.InternalMessageInfo

func (m *QueryRegisteredChainRequest) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

type QueryRegisteredChainResponse struct {
	ChainInfo string `protobuf:"bytes,1,opt,name=chainInfo,proto3" json:"chainInfo,omitempty"`
}

func (m *QueryRegisteredChainResponse) Reset()         { *m = QueryRegisteredChainResponse{} }
func (m *QueryRegisteredChainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredChainResponse) ProtoMessage()    {}
func (*QueryRegisteredChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{3}
}
func (m *QueryRegisteredChainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredChainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredChainResponse.Merge(m, src)
}
func (m *QueryRegisteredChainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredChainResponse proto.InternalMessageInfo

func (m *QueryRegisteredChainResponse) GetChainInfo() string {
	if m != nil {
		return m.ChainInfo
	}
	return ""
}

type QueryAllRegisteredChainsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisteredChainsRequest) Reset()         { *m = QueryAllRegisteredChainsRequest{} }
func (m *QueryAllRegisteredChainsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisteredChainsRequest) ProtoMessage()    {}
func (*QueryAllRegisteredChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{4}
}
func (m *QueryAllRegisteredChainsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisteredChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisteredChainsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisteredChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisteredChainsRequest.Merge(m, src)
}
func (m *QueryAllRegisteredChainsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisteredChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisteredChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisteredChainsRequest proto.InternalMessageInfo

func (m *QueryAllRegisteredChainsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRegisteredChainsResponse struct {
	RegisteredChains *RegisteredChains   `protobuf:"bytes,1,opt,name=registeredChains,proto3" json:"registeredChains,omitempty"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisteredChainsResponse) Reset()         { *m = QueryAllRegisteredChainsResponse{} }
func (m *QueryAllRegisteredChainsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisteredChainsResponse) ProtoMessage()    {}
func (*QueryAllRegisteredChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45081ff63ea4c0db, []int{5}
}
func (m *QueryAllRegisteredChainsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisteredChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisteredChainsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisteredChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisteredChainsResponse.Merge(m, src)
}
func (m *QueryAllRegisteredChainsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisteredChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisteredChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisteredChainsResponse proto.InternalMessageInfo

func (m *QueryAllRegisteredChainsResponse) GetRegisteredChains() *RegisteredChains {
	if m != nil {
		return m.RegisteredChains
	}
	return nil
}

func (m *QueryAllRegisteredChainsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "strangeloveventures.cns.cns.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "strangeloveventures.cns.cns.QueryParamsResponse")
	proto.RegisterType((*QueryRegisteredChainRequest)(nil), "strangeloveventures.cns.cns.QueryRegisteredChainRequest")
	proto.RegisterType((*QueryRegisteredChainResponse)(nil), "strangeloveventures.cns.cns.QueryRegisteredChainResponse")
	proto.RegisterType((*QueryAllRegisteredChainsRequest)(nil), "strangeloveventures.cns.cns.QueryAllRegisteredChainsRequest")
	proto.RegisterType((*QueryAllRegisteredChainsResponse)(nil), "strangeloveventures.cns.cns.QueryAllRegisteredChainsResponse")
}

func init() { proto.RegisterFile("cns/query.proto", fileDescriptor_45081ff63ea4c0db) }

var fileDescriptor_45081ff63ea4c0db = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0x53, 0x41,
	0x14, 0xcd, 0x94, 0x1a, 0xe9, 0x75, 0xd1, 0x32, 0x2d, 0x58, 0x5e, 0xc3, 0x6b, 0x79, 0xc5, 0x0f,
	0x90, 0xce, 0xb4, 0x15, 0xac, 0x85, 0x8a, 0xa4, 0x8a, 0xd2, 0x5d, 0xcd, 0x4a, 0xdd, 0xc8, 0xe4,
	0x39, 0x4e, 0x1f, 0xbc, 0xcc, 0xbc, 0xbe, 0x99, 0x04, 0x8b, 0xb8, 0xf1, 0x17, 0x08, 0x6e, 0xfc,
	0x2b, 0xfe, 0x01, 0x2d, 0xae, 0x0a, 0x6e, 0x5c, 0x89, 0x24, 0xfe, 0x10, 0x79, 0x33, 0x13, 0xf3,
	0xd9, 0xc4, 0x76, 0x91, 0x90, 0xb9, 0x33, 0xe7, 0xdc, 0x73, 0xee, 0x3d, 0x04, 0xe6, 0x63, 0xa9,
	0xe9, 0x71, 0x93, 0xe7, 0x27, 0x24, 0xcb, 0x95, 0x51, 0x78, 0x45, 0x9b, 0x9c, 0x49, 0xc1, 0x53,
	0xd5, 0xe2, 0x2d, 0x2e, 0x4d, 0x33, 0xe7, 0x9a, 0xc4, 0xd2, 0x7e, 0x82, 0x25, 0xa1, 0x84, 0xb2,
	0xef, 0x68, 0xf1, 0xcb, 0x41, 0x82, 0x8a, 0x50, 0x4a, 0xa4, 0x9c, 0xb2, 0x2c, 0xa1, 0x4c, 0x4a,
	0x65, 0x98, 0x49, 0x94, 0xd4, 0xfe, 0x76, 0xa1, 0xe8, 0x90, 0xb1, 0x9c, 0x35, 0xba, 0x95, 0xa0,
	0xa8, 0xe4, 0x5c, 0x24, 0xda, 0xf0, 0x9c, 0xbf, 0x7e, 0x74, 0xc4, 0x92, 0x7f, 0xaf, 0xaf, 0xc7,
	0x4a, 0x37, 0x54, 0x01, 0x10, 0x89, 0xb4, 0x3c, 0xee, 0x22, 0x5a, 0x02, 0xfc, 0xac, 0x90, 0x79,
	0x68, 0x99, 0x6a, 0xfc, 0xb8, 0xc9, 0xb5, 0x89, 0x9e, 0xc3, 0xe2, 0x40, 0x55, 0x67, 0x4a, 0x6a,
	0x8e, 0xab, 0x50, 0x76, 0x1d, 0x97, 0xd1, 0x1a, 0xba, 0x7d, 0x6d, 0x7b, 0x9d, 0x4c, 0x70, 0x45,
	0x1c, 0x78, 0x7f, 0xf6, 0xf4, 0xd7, 0x6a, 0xa9, 0xe6, 0x81, 0xd1, 0x0e, 0xac, 0x58, 0xe6, 0xda,
	0xa0, 0x4e, 0xdf, 0x18, 0x2f, 0xc3, 0xd5, 0xb8, 0x38, 0x1f, 0x3c, 0xb6, 0x2d, 0xe6, 0x6a, 0xdd,
	0x63, 0xb4, 0x07, 0x95, 0xf1, 0x40, 0xaf, 0xad, 0x02, 0x73, 0xee, 0xa9, 0x7c, 0xa3, 0x3c, 0xb6,
	0x57, 0x88, 0x12, 0x58, 0xb5, 0xe8, 0x6a, 0x9a, 0x0e, 0x11, 0x74, 0x3d, 0xe3, 0x27, 0x00, 0xbd,
	0xe9, 0x78, 0x83, 0x37, 0x89, 0x9b, 0x1b, 0xa9, 0x33, 0xcd, 0x89, 0xdb, 0x67, 0x6b, 0xab, 0xce,
	0x0d, 0xdb, 0x22, 0x87, 0x4c, 0x70, 0x8f, 0xad, 0xf5, 0x21, 0xa3, 0xaf, 0x08, 0xd6, 0xce, 0xef,
	0xe5, 0xd5, 0xbe, 0x80, 0x85, 0xe1, 0x4d, 0xf9, 0x96, 0x1b, 0x13, 0x67, 0x3a, 0x42, 0x38, 0x42,
	0x83, 0x9f, 0x0e, 0xf8, 0x98, 0xb1, 0xa4, 0xb7, 0xa6, 0xfa, 0x70, 0xba, 0xfa, 0x8d, 0x6c, 0x7f,
	0x99, 0x85, 0x2b, 0xd6, 0x08, 0xfe, 0x8c, 0xa0, 0xec, 0xb6, 0x89, 0xe9, 0x44, 0x79, 0xa3, 0x51,
	0x0a, 0x36, 0xff, 0x1f, 0xe0, 0x34, 0x44, 0x77, 0x3e, 0xfc, 0xf8, 0xf3, 0x69, 0xe6, 0x06, 0x5e,
	0xa7, 0x63, 0x90, 0xb4, 0x08, 0x79, 0x2f, 0xfa, 0xf8, 0x1b, 0x82, 0xf9, 0xa1, 0xa1, 0xe0, 0xfb,
	0xd3, 0x5b, 0x8e, 0x8f, 0x5f, 0xb0, 0x7b, 0x09, 0xa4, 0x57, 0xfd, 0xd0, 0xaa, 0xde, 0xc5, 0x3b,
	0x13, 0x55, 0xf7, 0xb6, 0xf5, 0xca, 0x86, 0x93, 0xbe, 0xf3, 0xf9, 0x7e, 0x8f, 0xbf, 0x23, 0x58,
	0x1c, 0x5e, 0x6f, 0x35, 0x4d, 0xf1, 0xde, 0x74, 0x4d, 0xe7, 0xa7, 0x3a, 0x78, 0x70, 0x49, 0xb4,
	0x77, 0x75, 0xcf, 0xba, 0xda, 0xc4, 0xe4, 0x42, 0xae, 0xf4, 0xfe, 0xc1, 0x69, 0x3b, 0x44, 0x67,
	0xed, 0x10, 0xfd, 0x6e, 0x87, 0xe8, 0x63, 0x27, 0x2c, 0x9d, 0x75, 0xc2, 0xd2, 0xcf, 0x4e, 0x58,
	0x7a, 0x49, 0x45, 0x62, 0x8e, 0x9a, 0x75, 0x12, 0xab, 0x46, 0x3f, 0xe7, 0xc6, 0x00, 0xe9, 0x5b,
	0xfb, 0x6d, 0x4e, 0x32, 0xae, 0xeb, 0x65, 0xfb, 0x47, 0x75, 0xf7, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0xf4, 0x49, 0xab, 0x53, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a registered chain from RegisteredChains.
	RegisteredChain(ctx context.Context, in *QueryRegisteredChainRequest, opts ...grpc.CallOption) (*QueryRegisteredChainResponse, error)
	// Queries a list of RegisteredChains items.
	RegisteredChainsAll(ctx context.Context, in *QueryAllRegisteredChainsRequest, opts ...grpc.CallOption) (*QueryAllRegisteredChainsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/strangeloveventures.cns.cns.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredChain(ctx context.Context, in *QueryRegisteredChainRequest, opts ...grpc.CallOption) (*QueryRegisteredChainResponse, error) {
	out := new(QueryRegisteredChainResponse)
	err := c.cc.Invoke(ctx, "/strangeloveventures.cns.cns.Query/RegisteredChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredChainsAll(ctx context.Context, in *QueryAllRegisteredChainsRequest, opts ...grpc.CallOption) (*QueryAllRegisteredChainsResponse, error) {
	out := new(QueryAllRegisteredChainsResponse)
	err := c.cc.Invoke(ctx, "/strangeloveventures.cns.cns.Query/RegisteredChainsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a registered chain from RegisteredChains.
	RegisteredChain(context.Context, *QueryRegisteredChainRequest) (*QueryRegisteredChainResponse, error)
	// Queries a list of RegisteredChains items.
	RegisteredChainsAll(context.Context, *QueryAllRegisteredChainsRequest) (*QueryAllRegisteredChainsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RegisteredChain(ctx context.Context, req *QueryRegisteredChainRequest) (*QueryRegisteredChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredChain not implemented")
}
func (*UnimplementedQueryServer) RegisteredChainsAll(ctx context.Context, req *QueryAllRegisteredChainsRequest) (*QueryAllRegisteredChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredChainsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strangeloveventures.cns.cns.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegisteredChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strangeloveventures.cns.cns.Query/RegisteredChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredChain(ctx, req.(*QueryRegisteredChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredChainsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRegisteredChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredChainsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strangeloveventures.cns.cns.Query/RegisteredChainsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredChainsAll(ctx, req.(*QueryAllRegisteredChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "strangeloveventures.cns.cns.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RegisteredChain",
			Handler:    _Query_RegisteredChain_Handler,
		},
		{
			MethodName: "RegisteredChainsAll",
			Handler:    _Query_RegisteredChainsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cns/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredChainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredChainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredChainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredChainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredChainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredChainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainInfo) > 0 {
		i -= len(m.ChainInfo)
		copy(dAtA[i:], m.ChainInfo)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainInfo)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisteredChainsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisteredChainsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisteredChainsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisteredChainsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisteredChainsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisteredChainsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.RegisteredChains != nil {
		{
			size, err := m.RegisteredChains.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRegisteredChainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegisteredChainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainInfo)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRegisteredChainsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRegisteredChainsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RegisteredChains != nil {
		l = m.RegisteredChains.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredChainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredChainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredChainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredChainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredChainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredChainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisteredChainsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisteredChainsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisteredChainsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisteredChainsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisteredChainsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisteredChainsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredChains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisteredChains == nil {
				m.RegisteredChains = &RegisteredChains{}
			}
			if err := m.RegisteredChains.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
